services:
    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./src:/var/www/html
            - ./certbot/www:/var/www/certbot
            - ./certbot/conf:/etc/letsencrypt
        depends_on:
            - laravel_php_fpm

    laravel_php_fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_php_fpm
        volumes:
            - ./src:/var/www/html
        environment:
            - APP_ENV=local
        working_dir: /var/www/html

    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - ./certbot/conf:/etc/letsencrypt
            - ./certbot/www:/var/www/certbot
        entrypoint: /bin/sh -c 'trap exit TERM; while :; do sleep 1 & wait $${!}; done'

networks:
    default:
        driver: bridge
