services:
    laravel_php_fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_php_fpm
        volumes:
            - .:/var/www/html
        environment:
            DB_CONNECTION: ${DB_CONNECTION:-mysql}
            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT:-25060}
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: laravel_nginx
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "${APP_PORT:-80}:80"
        depends_on:
            - laravel_php_fpm
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
