services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - ./laravel_app:/var/www/html
        ports:
            - "${APP_PORT:-8000}:80"
        environment:
            DB_CONNECTION: ${DB_CONNECTION:-mysql}
            DB_HOST: ${DB_HOST:-127.0.0.1}
            DB_PORT: ${DB_PORT:-3306}
            DB_DATABASE: ${DB_DATABASE:-laravel_db}
            DB_USERNAME: ${DB_USERNAME:-root}
            DB_PASSWORD: ${DB_PASSWORD:-}
        depends_on:
            - mysql
            - phpmyadmin
        networks:
            - laravel

networks:
    laravel:
