services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: laravel_app
        volumes:
            - ./laravel_app:/var/www/html
        ports:
            - "${APP_PORT:-8000}:80"
        environment:
            DB_CONNECTION: ${DB_CONNECTION:-mysql}
            DB_HOST: ${DB_HOST} # Your DigitalOcean database host
            DB_PORT: ${DB_PORT:-25060} # DigitalOcean typically uses port 25060
            DB_DATABASE: ${DB_DATABASE}
            DB_USERNAME: ${DB_USERNAME}
            DB_PASSWORD: ${DB_PASSWORD}
        networks:
            - laravel

networks:
    laravel:
