name: Deploy Laravel to VPS

on:
  push:
    branches:
      - "production"

jobs:
  deploy:
    name: CI/CD to VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            REPO="https://github.com/RafiRhnnn/elearning.git"
            DIR="${{ secrets.VPS_PATH }}"
            CONTAINER="laravel_app"
            BRANCH="production"

            echo "Cek git"
            if ! command -v git &>/dev/null; then
              echo "Install git..."
              sudo apt-get update && sudo apt-get install -y git
            fi

            echo "Cek docker"
            if ! command -v docker &>/dev/null; then
              echo "Install docker..."
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker $USER
            fi

            echo "Cek docker compose"
            if ! docker compose version &>/dev/null; then
              echo "Install docker compose plugin..."
              mkdir -p ~/.docker/cli-plugins
              curl -SL https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64 \
                -o ~/.docker/cli-plugins/docker-compose
              chmod +x ~/.docker/cli-plugins/docker-compose
            fi

            echo "Cek nodejs 20"
            if ! command -v node &>/dev/null || ! node -v | grep -q "v20"; then
              echo "Install Node.js 20..."
              curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            echo "Clone atau pull repo"
            if [ ! -d "$DIR/.git" ]; then
              echo "Clone repo..."
              git clone --branch $BRANCH $REPO $DIR
            else
              echo "Pull update..."
              cd $DIR
              git fetch 
              git pull origin $BRANCH
            fi

            echo "Menyimpan .env untuk Laravel"
            # Ensure the directory exists before writing the file
            mkdir -p "${{ secrets.VPS_PATH }}"
            echo "${{ secrets.LARAVEL_ENV }}" > ${{ secrets.VPS_PATH }}/.env

            echo "Menyiapkan environment variables untuk Docker Compose"
            # Clear previous .env.deploy content to avoid appending duplicates
            > "$DIR/.env.deploy"
            echo "APP_PORT=${{ secrets.APP_PORT }}" >> "$DIR/.env.deploy"
            echo "DB_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }}" >> "$DIR/.env.deploy"
            echo "DB_HOST=${{ secrets.DB_HOST }}" >> "$DIR/.env.deploy"
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> "$DIR/.env.deploy"
            echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> "$DIR/.env.deploy"
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> "$DIR/.env.deploy"
            echo "PHPMYADMIN_PORT=${{ secrets.PHPMYADMIN_PORT || 8080 }}" >> "$DIR/.env.deploy" # Added PHPMYADMIN_PORT

            echo "Masuk direktori $DIR";
            cd $DIR
            echo "Restart Docker Compose"
            # Use --remove-orphans to remove containers not defined in the compose file
            docker compose down --remove-orphans
            docker compose --env-file .env up -d --build

            echo "Menunggu Laravel siap..."
            # Wait for the Laravel application to be ready
            until docker exec $CONTAINER php artisan --version > /dev/null 2>&1; do
              echo "Menunggu Laravel container..."
              docker container start $CONTAINER
              sleep 2
            done

            echo "Laravel siap!"
            echo "composer install"
            docker exec $CONTAINER composer install --optimize-autoloader --no-dev
            echo "buat key"
            docker exec $CONTAINER php artisan key:generate
            echo "artisan migrate"
            docker exec $CONTAINER php artisan migrate --force
             docker exec $CONTAINER php artisan storage:link
            docker exec $CONTAINER php artisan config:cache
            docker exec $CONTAINER php artisan route:cache
            docker exec $CONTAINER php artisan view:cache
            echo "Selesai! Aplikasi Laravel telah dideploy."
